export const ERROR_NO_INTERNET_CONNECTION = 'ERROR_NO_INTERNET_CONNECTION',
    ONLINE_BACK = 'ONLINE_BACK',
    COMMAND_LAZY_IMAGE_LOAD = 'COMMAND_LAZY_IMAGE_LOAD',
    MODE_LAZY_IMAGE_MANUAL = ' MODE_LAZY_IMAGE_MANUAL',
    MODE_LAZY_IMAGE_WHEN_VISIBLE = 'MODE_LAZY_IMAGE_WHEN_VISIBLE'